{% set name = "numba_quaternion" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/n/numba-quaternion/numba_quaternion-{{ version }}.tar.gz
  sha256: c2054ab7a2e4103763832861542ede6654b49918430942b10232b6a9ee95c312

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - pip
    - uv-build >=0.9,<0.13
  run:
    - python >={{ python_min }}
    - numba >=0.59
    - numpy >=1.23
    # numba needs scipy for linear algebra in jitted code
    - scipy >=1.10

test:
  source_files:
    - tests
  imports:
    - numba_quaternion
  commands:
    - pip check
    - pytest tests -v
  requires:
    - python {{ python_min }}
    - pip
    - pytest

about:
  home: https://github.com/ickc/python-numba_quaternion
  summary: Quaternion operations that can be used within Numba-jit functions.
  license: BSD-3-Clause
  license_file: LICENSE
  doc_url: https://ickc.github.io/python-numba_quaternion
  dev_url: https://github.com/ickc/python-numba_quaternion

extra:
  recipe-maintainers:
    - ickc
